name: Deploy to Surge

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest                                    
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Actualiza la versión a v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Actualiza la versión a v3
        with:
          node-version: '14'

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: surge --project ./ --domain pagina.web.surge.sh --token $SURGE_TOKEN

