name: Deploy to Surge

on:
  push:
    branches:
      - main  # Se ejecuta cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar en Surge
        run: surge ./ --domain tu-dominio.surge.sh --token ${{ secrets.SURGE_TOKEN }}
